### ISSUE TITLE
Publish a non-minimized bundle in Unpkg

### ISSUE THREAD

**Issue by ridomin** [MQTTCool/mqtt.cool-lib-client-javascript#1]
The current unpkg dist folder only contains the minimized bundle, what makes almost impossible to debug.

**Comment by acarioni** [comment]
If you need a plain version of the library, you can make a custom build.

You have only to comment out the _compiler_ directive, just above the _outputOptions_ block, in the files `tools/build_web.js` and `tools/build_node.js` (row number 128 for `build_web.js` and row number 77 for `build_node.js`). 

The outputs are saved in `tools/dist-web` and `tools/dist-node`.
